apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mainshell
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mainshell
      zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: mainshell
        version: "1.0.0"
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
    spec:
      containers:
        - name: mainshell-ctr
          image: metamagicglobal/mainshell:k8 
          imagePullPolicy: Always
          ports:
          - containerPort: 80                               
