apiVersion: v1
kind: Service
metadata:
  name: mainshell-svc
  namespace: shoppingportal
  labels:
    name: mainshellsvc
spec:
  type: NodePort
  selector:
        name: mainshell
        version: "1.0.0"
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: my-http-port
